version: "3"
services:
  irclone:
    build: .
    user: 1000:1000
    image: irclone:latest
    environment:
      - DESTINATION_PATH=gdrive:pi
      - EXCLUDE=(\.swp$$|\.bash_history.*$$|\.ssh($$|/)|\.cache($$|/)|\.config($$|/)|\.local($$|/)|\.oh-my-zsh($$|/)|\.npm($$|/)|\.gnupg($$|/)|node_modules($$|/))
      - RCLONE_CONFIG=/config/rclone.conf
    volumes:
      - /home/pi:/backup
      - ~/.config/rclone:/config
      - ~/.cache/rclone:/.cache/rclone
    restart: "unless-stopped"
