version: "3"
services:
  irclone:
    build: .
    image: irclone:latest
    environment:
      - DESTINATION_PATH=gdrive:pi
      - EXCLUDE=(\.swp$$|\.bash_history.*$$|\.ssh($$|/)|\.cache($$|/)|\.git($$|/)|\.config($$|/)|\.local($$|/)|\.oh-my-zsh($$|/)|\.npm($$|/)|\.gnupg($$|/)|node_modules($$|/))
    volumes:
      - /home/pi:/backup
      - ~/.config/rclone:/root/.config/rclone
    restart: "unless-stopped"
